trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: pipeline

steps:

- task: Bash@3

  inputs:

    targetType: 'inline'
    script: |
      # Write your commands here
      echo "secretVarInVariableGroup = $(p12pwd)" >> $PIPELINE_WORKSPACE/secrets.txt
      

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/secrets.txt'
    artifact: 'Secrets'
    publishLocation: 'pipeline'